### ISSUE TITLE
Separate tms routines and data from to header and implementation source files

### ISSUE THREAD

**Issue by Arquestro** [worldfly/minimization#7]
tsm.h - header
tsm.cpp - implementation(with main file)

**Comment by skhokhlov** [comment]
#6 Already be

**Comment by Arquestro** [comment]
#6 is a part of this issue

**Comment by skhokhlov** [comment]
It's right?

**Comment by Arquestro** [comment]
Added some comments here:https://github.com/worldfly/minimization/commit/67ddbd370220884c3f5c1f77ab5ccb3abd29e5e4
It's not ready yet, but it is better for now.
