### ISSUE TITLE
CI connection

### ISSUE THREAD

**Issue by skhokhlov** [worldfly/minimization#8]
I want build and test project on Travis. [We on Travis](https://travis-ci.org/worldfly/minimization)
[Travis C++ example](https://docs.travis-ci.com/user/languages/cpp/)

**Comment by skhokhlov** [comment]
I think that would be great if it make someone who is not maintainer. It could be useful.

**Comment by skhokhlov** [comment]
Hey @dmkz! You are also concerned. What do you think about it?

**Comment by Arquestro** [comment]
I suppose it's too early too integrate a CI service ATM

**Comment by skhokhlov** [comment]
CI is never too early

**Comment by skhokhlov** [comment]
We need run, not only build project

**Comment by Arquestro** [comment]
It LGTM now
